---

- name: Set  root password
  shell: echo root:{{ root_passwd }} | sudo chpasswd
  become: yes

- name: Copy database dump file
  copy:
   src: sshd_config
   dest: /etc/ssh/sshd_config
  become: yes
  notify: restart ssh

